### PR TITLE
Rename blueprint .gitignore to gitignore

### PR DESCRIPTION
**Pull request by mwpastore**
blprnt will automatically rename it

### CODE REVIEW

**Comment by mwpastore** [comment]
@ghedamat Thoughts on this? blprnt will automatically rename `gitignore` to `.gitignore`. As it stands now, `node_modules` and a bunch of other garbage gets checked in on the initial commit (i.e. on `ember new -b`), and anyone using this blueprint will have to clean it up manually (as I had to).

**Comment by ghedamat** [comment]
I'll have to summon @achambers for this one, I know he had a conversation with the ember-cli maintainers about this very problem

**Review by achambers — APPROVED** [review]
Legendary

**Comment by achambers** [comment]
Thanks a million. Will release on Tuesday. Not going to get to it before then. Sorry

**Comment by ibroadfo** [comment]
could this get pushed to npm please? :)

**Comment by achambers** [comment]
@ibroadfo / @mwpastore Finally, pushed to npm as v0.0.9.  Massive apologies for the complete lack of promptness on this. Bad maintainer.

**Comment by ibroadfo** [comment]
Thanks! Don't sweat it. :)

**Pull request merged**
